<?php


namespace App\Repositories\User;


use App\Entities\User\User;
use App\Repositories\BaseRepository;
use Illuminate\Support\Facades\Hash;
use Ramsey\Uuid\Uuid;

class UserRepository extends BaseRepository
{
    public function __construct()
    {
        $this->model = new User();
    }

    public function create(array $data)
    {
        $data['id'] = Uuid::uuid4()->toString();
        $data['password'] = Hash::make($data['password']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update(array $data, $id)
    {
        if(isset($data['password'])){
            unset($data['password']);
        }
        return parent::update($data, $id); // TODO: Change the autogenerated stub
    }
}
